infra/docker-compose.yml

triggers release for adding upsert support

fix: tests and trigger release

---

infra/docker-compose.yml
package.json
src/lib/StorageFileApi.ts

upload was not using custom fetch when it was provided

use custom fetch for uploads

---

src/lib/StorageBucketApi.ts
src/lib/StorageFileApi.ts
src/lib/fetch.ts
src/lib/helpers.ts

Ref: https://github.com/supabase/supabase-js/issues/389

fix: prefer global fetch to cross-fetch

---

src/lib/helpers.ts

Ref: https://github.com/supabase/storage-js/pull/43#discussion_r814736384

fix: illegal invocation on fetch

---

package.json

fix: types in package.json

---

README.md
src/lib/StorageBucketApi.ts

Provided a quickstart guide in the readme to showcase how one could get up and running using this module by itself, not as part of `supabase-js`
Fixes #45

Provide quickstart guide

---

src/lib/StorageBucketApi.ts

fix: typo in updateBucket jsdoc

---

src/packages/StorageFileApi.ts

matches the method name createSignedUrl

return signed url as signedUrl

---

.gitignore
infra/docker-compose.yml
jest.config.js
package-lock.json
package.json
test/__snapshots__/storageApi.test.ts.snap
test/__snapshots__/storageFileApi.test.ts.snap
test/fixtures/upload/file-2.txt
test/fixtures/upload/file.txt
test/storageApi.test.ts
test/storageFileApi.test.ts

Adds more tests around the Object API and general test refactor
No tests were present for the object api
new tests are added

Increased test coverage

---

src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Adds transform option to the `download` method

transform option to download method

---

src/lib/types.ts
src/packages/StorageFileApi.ts

Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

feat: image transformation (#128)

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml

fix: upgrade node version CI

---

package-lock.json
package.json

fix: run npm audit fix

---

.github/workflows/ci.yml

chore: ensure build passes in CI

---

src/lib/types.ts

clarified quality is between 20 and 100

chore: docs for quality and format

---

infra/docker-compose.yml
infra/postgres/dummy-data.sql
infra/storage/Dockerfile
src/packages/StorageFileApi.ts
test/__snapshots__/storageApi.test.ts.snap
test/storageApi.test.ts
test/storageFileApi.test.ts

Feature
Implements Signed Upload URL methods

feat: signed upload url

---

package-lock.json
package.json
src/lib/helpers.ts
test/storageFileApi.test.ts

Part of fixing https://github.com/supabase/supabase-js/issues/612

fix: use @supabase/node-fetch

---

package-lock.json
package.json
src/lib/helpers.ts
test/storageFileApi.test.ts

This reverts commit dc1d067781f562d5fbfe83109527d57b2d9899b3, reversing changes made to b2e3486222126620cc65a5a1c1f967d25b4fb099.

fix: Revert "Merge pull request #175 from supabase/fix/supabase-node-fetch"

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml

fix: bump node version in ci

---

.github/workflows/ci.yml
jest.config.js
package.json

Upload coverage to coveralls, check https://coveralls.io/github/supabase/storage-js

chore: upload test coverage to coveralls

---

jest.config.js
test/storageBucketApi.test.ts
test/storageFileApi.test.ts
test/storageFileApiErrorHandling.test.ts

Adds test coverage to error responses in file and bucket APIs

test error responses in file and bucket apis. coverage 84%

---

src/packages/StorageFileApi.ts

clarify list endpoint lists folders too

fix: update docs for list endpoint
