supabase/storage-js

src/lib/StorageFileApi.ts

fixes https://github.com/supabase/storage-api/issues/18
Looks like the non file values need to be sent before the file fields in form-data as mentioned [here](https://github.com/fastify/fastify-multipart/issues/146#issuecomment-681874488) and it is the intended behaviour.

fix: cacheControl header when uploading

---

infra/docker-compose.yml
infra/postgres/storage-schema.sql
src/lib/StorageBucketApi.ts
src/lib/types.ts
test/__snapshots__/storageApi.test.ts.snap
test/storageApi.test.ts

Adding a public option when creating and updating a bucket.
Related to https://github.com/supabase/storage-js/issues/11
There is no method for creating a public bucket. 
Users can create public bucket by calling `await storage.createBucket(newPublicBucketName, { public: true })`

feat: Added public option to createBucket method

---

src/lib/StorageFileApi.ts
test/__snapshots__/storageFileApi.test.ts.snap
test/storageFileApi.test.ts

Introducing a new feature to add a method to easily retrieve public URLs of object uploaded to storage. 
Related PR on storage-api
https://github.com/supabase/storage-api/pull/19
There is not an easy way of getting a public URL of an object. 
There will be a method where you can just pass the bucket and the path, and it will return full URL of the object. 
I don't know if we need a method like this when all it is doing is just concatenating Supabase URL, bucket name, and path with '/object/public' in the middle, but personally I would appreciate if the SDK could handle the concatenation. 
Also, I was not sure if implementing something like this has been discussed internally, so if there is already a plan for it, and is different from the code that I wrote, please feel free to just close …

feat: Added a method to get public URL of an object

---

package.json
src/lib/StorageFileApi.ts
test/__snapshots__/storageFileApi.test.ts.snap

keeps it consistent wth createSignedURL since that returns an absolute URL. 
We were returning the relative URL in `data.publicURL` and absolute URL in `publicURL`. We should keep both of these the same

fix: return the full URL in both places

---

src/lib/StorageFileApi.ts
src/lib/types.ts

feature
Closes #7 
Currently there is no option overwrite an object on upload.
Introduces an `upsert` flag with default value false, which sends `x-upsert` in headers to storage api.

ptch: add upsert flag in file options for upload

---

infra/postgres/storage-schema.sql

Given a bucket "a"  and an object name "123/456", and a bucket "b" and an object/folder name "123", when selecting bucketname="a" and prefix="":
Before the fix:
If the latter doesn't exist, a row with only name="123" populated and the other columns being NULL is returned.
If the latter exists, name="123" is left joined with the row with object/folder name "123", and then filtered out by the `WHERE ... objects.bucket_id=bucketname` clause.
After the fix:
The row with object/folder name "123" isn't left joined, so a row with only name="123" populated and the other columns being NULL is returned correctly.

Prevent empty results when selecting folder(s) in one bucket that match an object name in another bucket

---

src/SupabaseStorageClient.ts
src/lib/StorageBucketApi.ts
src/lib/StorageFileApi.ts
src/lib/fetch.ts

This PR adds the ability to provide a custom `fetch` implementation as an option - this is most useful for environments where `cross-fetch` is not supported, for instance Cloudflare Workers or Vercel Edge Functions.
This is related to https://github.com/supabase/supabase-js/issues/154, and I believe a similar option would need to be added to the other libraries using `cross-fetch` before being finally added to `supabase-js`.
At the moment, `cross-fetch` is always used in all environments.
There is a new option `fetch` that can be provided to override `cross-fetch` with an alternative library (or the native `fetch`):
```js
import { SupabaseStorageClient } from '@supabase/storage-js'
const url = '...'
const headers = {}
const fetch = ...
const storage = new SupabaseStorageClient(url, …
```

feat: allow providing custom fetch implementation

---

.github/workflows/release.yml

releases are failing: https://github.com/supabase/storage-js/runs/4137162898?check_suite_focus=true

fix: release error

---

src/lib/StorageFileApi.ts

Bug fix - addresses [#4633](https://github.com/supabase/supabase/issues/4633)
Calling 
```Javascript 
storage.from(bucketName).upload('/file-name.ext', aFile)
``` 
or 
```Javascript
storage.from(bucketName).upload('folder//file-name.ext', aFile)
``` 
creates a folder with no name. This new nameless folder cannot be deleted. 
Cleans up upload path by removing any leading `/` or `//` anywhere in the path
Alternatively, this could be a regex test that throws an error when `//` or leading `/` is detected

fix/empty-name-folder: Removes leading / or "//" anywhere else in new path

---

src/lib/StorageFileApi.ts

Makes the "copy" API available in the client as described in this issue: https://github.com/supabase/storage-js/issues/29 (I believe this issue is incorrectly marked as closed.)
n/a
I works just like the `move()` method, but hits up the `/object/copy` endpoint instead.
n/a

Feat: Copy object

---

src/lib/StorageFileApi.ts

For consistency with `createSignedUrl()`.

fix: return whole URLs from `createSignedUrls()` instead of just paths

---

src/lib/types.ts

A simple non-breaking change that adds the new search param (added in https://github.com/supabase/storage-api/pull/127) to the list function.

feat: add search param to list function

---

package-lock.json
package.json
src/index.ts
src/lib/StorageBucketApi.ts
src/lib/StorageFileApi.ts
src/lib/errors.ts
src/lib/fetch.ts
src/lib/helpers.ts
test/__snapshots__/storageApi.test.ts.snap

Fixes #55.
There are some type errors, and functions return everything with `| null`, making it difficult for end-users to work with.
Functions now return type unions, which are more correct and easier to work with.
I've labelled this as `feat` instead of `chore` as it should be treated as a **breaking change** because it may show new type errors to existing users.

feat: improve function return types

---

README.md
src/lib/StorageBucketApi.ts
src/lib/StorageFileApi.ts
src/lib/helpers.ts
tsconfig.module.json

Fixes #9 
Currently, the `uploadOrUpdate` function (so automatically the `upload` and `update` functions as well), only returns a `Key: value` pair that represents the file path prefixed by the bucket id.
This path cannot be then passed to the `download` method as the download doesn't need the bucket id prefix.
By simply adding 2 more `Key: value` pairs to the returned `data` object, we can provide more useful information in the returned object:
```javascript
{
Key: the old path, for backwards compatibility
downloadPath: the path not prefixed by the bucket ID
bucketId: the id of the bucket
}
```
By also providing the bucket ID in the returned data, we give users the full set on information required to be able to call `download`, as I assume that the data returned from `upload` will then …

Improve `uploadOrUpdate` returned data.

---

src/lib/StorageBucketApi.ts
src/lib/StorageFileApi.ts
src/lib/helpers.ts
test/__snapshots__/storageFileApi.test.ts.snap
test/storageFileApi.test.ts
tsconfig.module.json

Fixes #53 and #27 
Currently, `getPublicUrl` is looking like this:
```javascript
getPublicUrl(
path: string
): {
data: { publicURL: string } | null
error: Error | null
publicURL: string | null
} {
try {
const _path = this._getFinalPath(path)
const publicURL = `${this.url}/object/public/${_path}`
const data = { publicURL }
return { data, error: null, publicURL }
} catch (error) {
return { data: null, error, publicURL: null }
}
}
```
Which is not ideal because:
1. The `try... catch` doesn't really make much sense as all that happens inside the function, at least to  my understanding, is string concatenation of values that are not null thanks to typescript.
2. The error will always be `null`.
3. The return type is inconsistent with the other methods. They all return `{data, error}` and this …

Improve `getPublicUrl`

---

.gitignore
src/lib/StorageFileApi.ts

as a return parameter and in the path. Just returning the path without the bucket id makes it easier to pass the value in to other storage-js functions. Also not calling it Key -- was uppercase and not as clear as just calling it path.

upload, update: don't return bucketId

---

.github/workflows/ci.yml
.github/workflows/release.yml
.releaserc.json

What kind of change does this PR introduce?
Sets up the next branch as an npm prerelease
What is the current behavior?
There is currently no prerelease pipeline.
What is the new behavior?
Pushes to the next branch will be included as an npm prerelease under the next tag.

build(release-next): sets up the next branch as an npm prerelease

---

package.json

It looks like we were doubling up on release configs

fix: remove release config from package.json

---

src/lib/StorageFileApi.ts

fixes https://github.com/supabase/storage-js/issues/78
Encodes URLs in `createSignedUrl`, `createSignedUrls` and `getPublicUrl`
this should ideally be done in the api server, but doing this breaking change at the client library first, so when we do it at the backend, only folks who are using the api directly will need to upgrade.

fix: encode all urls

---

src/lib/StorageFileApi.ts

signedURL used to return a url directly and inside the data object. This is inconsistent. Now we always return values inside a data object only.

fix: signed URLs return value

---

src/lib/StorageBucketApi.ts
test/storageApi.test.ts

instead of cherry picking only name - we still do this in the types though.
also ensures data is always an object.
Fixes [#6](https://github.com/supabase/storage-js/issues/6)

fix: createBucket pass through all values returned by backend

---

src/lib/types.ts

Previously accessing metadata.contentType would throw a type error since we set the type to an empty object.

fix: metadata type

---

src/index.ts

removing the change we added for backward compatibility here https://github.com/supabase/storage-js/issues/46

fix: only export StorageClient

---

src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Bug fix
The copy method return signature was incorrect
we now returns a path key to be consistent with the other methods

fix: consistent return types for copy

---

src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

feature
Adds the `download` option to the following methods:
- `getPublicUrl`
- `getSignedUrl`
- `getSignedUrls`
Support downloading a file via url https://github.com/supabase/storage-api/pull/195

feat: download file via url

---

infra/storage/Dockerfile
src/lib/types.ts
src/packages/StorageFileApi.ts

fix
Revised `resize` option on `transform`
The available values are:
- cover
- contain
- fill

fix: revised resize option

---

infra/docker-compose.yml
infra/storage/Dockerfile
src/lib/types.ts
src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Feature
Introduced a `format` option to request the image in a different format.
Currently, the only value allowed is `origin` which will force the image to be returned with its original format.
If not provided we will automatically optimise the image using webp
```ts
await storage.from('bucket').download(uploadPath, {
transform: {
width: 200,
height: 200,
format: 'origin',
},
})
```

feat: format option for webp support

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml

semantic-release now requires node 18

update deps to fix release ci

---

infra/storage/Dockerfile
src/lib/types.ts
src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Feature
Implement `quality` option for image transformation

feat: quality option, image transformation

---

src/lib/fetch.ts

on `handleError` method, we call error.json() without a catch block. It can end up with an unhandled promise error. This kind of error can kill a Nodejs application 
add catch block and reject with a StorageUnknownError

fix: unhandled promise error when response has invalid json format

---

src/packages/StorageFileApi.ts

Undici >v5.12.0 requires this.
bug fix
https://github.com/supabase/storage-js/issues/146
Allows the following to go through to the request
```js
await supabase.storage.from('some-bucket').upload('filename', someReadableStream, { duplex: 'half' })
```

Update upload methods to allow duplex option to be passed in

---

src/lib/types.ts

Bug fix
With #147 PR merged. There is no `duplex` key available in `FileOptions` and still being accessed. Which is failing unit tests. And also not allowing to pass `duplex` in typescript projects.
This PR included `duplex` parameter in `FileOptions` interface.
Add any other context or screenshots.
Before
After

Fix typescript interface `FileOptions` does not have `duplex`

---

src/packages/StorageBucketApi.ts

Bug fix
Pass `null` to `fileSizeLimit`, `allowedMimeTypes` to remove the constraint

fix: allow null on bucket constraints

---

src/packages/StorageFileApi.ts

docs update
Bump signed URL expiry to 2h

docs: signed upload url expiry time

---

package-lock.json
package.json
src/lib/helpers.ts
test/storageFileApi.test.ts

2nd attempt at https://github.com/supabase/storage-js/pull/175.
https://github.com/supabase/postgrest-js/pull/470 has been out for a week with no reported issues.

fix: use @supabase/node-fetch

---

src/packages/StorageFileApi.ts

Bug fix for #170 
Currently, only part of the path (not including the bucket) of the uploaded file is returned even though the API returns both the ID and full path of the file: [source](https://supabase.github.io/storage-api/#/object/post_object__bucketName___wildcard_)
The new behavior is for the response of the upload client call to return the id and full path in addition to the path.

Return ID and full path of uploaded file

---

src/packages/StorageFileApi.ts

Update return interface in upload and update functions StorageFileApi.ts to return id and fullPath since the uploadOrUpdate returns fullPath and id which are used in multiple cases when uploading/updating a file
Bug fix
the id and full path are not returned in the upload and update functions in StorageFileApi.ts
the id and full path are returned in the upload and update functions in StorageFileApi.ts

add id and fullPath to update and upload functions response

---

infra/storage/Dockerfile
src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Feature
Cannot overwrite files with signed URLs
Allow passing `upsert: true` to get a signed upload URL that will allow to overwrite files

feat: signed upload URL upsert

---

infra/storage/Dockerfile
src/lib/fetch.ts
src/lib/helpers.ts
src/lib/types.ts
src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Feature
Adds support for custom metadata on objects:
```ts
const res = await storage.from(bucketName).upload(uploadPath, file, {
metadata: {
custom: 'metadata',
second: 'second',
third: 'third',
},
})
```
added 2 new methods, exists and info
**Info**
fetches the information about this object
```ts
const {data: obj} = await storage.from(bucketName).info(uploadPath)
obj.id
obj.metadata
```
**Exists**
Check if a file exists
```ts
const {data: exists} = await storage.from(bucketName).exists(uploadPath)
console.log(exists) // true / false
```
Relates to https://github.com/supabase/storage/issues/439

feat: custom-metadata, exists, info methods

---

package.json
src/packages/StorageFileApi.ts

Bug fix
- Fix the ordering of the metadata field in the multiform data

fix: metadata ordering on multipart form/data

---

src/lib/fetch.ts
src/packages/StorageFileApi.ts

Fix the error handling of `upload`, `update` and `uploadToSignedUrl` APIs so that they properly return `StorageError` instead of API's error schema.
Multiple issues and PRs have been discussing this error for over a year. #214 #165 
There are a bunch of helper functions at `lib/fetch.ts` that catch errors returned by the server and construct `StorageError` instance. Nearly all requests are using these helpers, except for `uploadOrUpdate` and `uploadToSignedUrl` in `StorageFileApi`, making their return types inconsistent:
Typescript declarations say the error returns are like:
```typescript
{
data: null,
error: StorageError
}
```
However, without the helper functions, they actually return the error schema:
```typescript
{
data: null,
error: { error: string, message: string, statusCode: …
```

fix: Properly handle errors in Upload Api  (related to StorageError)

---

src/lib/errors.ts
src/lib/fetch.ts
src/lib/helpers.ts
src/packages/StorageFileApi.ts
test/storageFileApi.test.ts

Bug fix
Uploading binary objects or streams results in improperly serialized data. This issue was introduced by #216 
Only stringify plain objects to ensure Buffer, FormData, Uint8Array, etc are handled correctly
Add `statusCode` to `StorageApiError` this gives access to the error code sent in the json payload from the storage api, and maintains the same `statusCode` values present before #216 in case anyone depends on it.
Issue reported in a comment on the original PR here: https://github.com/supabase/storage-js/pull/216#issuecomment-2848783707

fix: resolve regression with uploading files introduced by #216

---

src/packages/StorageBucketApi.ts
test/storageBucketApi.test.ts

Feature
Storage lib is initialized using the same host as all other Supabase APIs. This zone does not allow uploading of large files.
Initialize storage lib using new `project-ref.storage.supabase.co/v1` URI which supports uploads up to 500GB
This is specific to the Supabase infrastructure
`project-ref.supabase.co/storage/v1` -> `project-ref.storage.supabase.co/v1`

feat: use dedicated storage host for storage lib (allows >50GB uploads)

---

src/lib/types.ts

Preview Feature
changed bucket type to `ANALYTICS`

fix: consistent bucket type name

---

src/lib/types.ts
src/packages/BlobDownloadBuilder.ts
src/packages/StorageFileApi.ts
src/packages/StreamDownloadBuilder.ts
test/storageFileApi.test.ts
test/storageFileApiErrorHandling.test.ts

Refactor? Feature?
Related to #72 
Right now the library only allows download as `Blob`.
This PR allows downloading as stream.
The following code is made possible:
```typescript
// Regular download (returns Blob)
const { data: blob } = await storage.from(bucket).download(path)
// Stream download (returns ReadableStream)
const { data: stream } = await storage.from(bucket).download(path).asStream()
```
This is done by returning a class that either implements `PromiseLike<Blob>` or `PromiseLike<ReadableStream>`.
Thus 2 new classes were added.
I have considered adding 1 class only such that there will only be `DownloadBuilder<Blob | ReadableStream>` but it may cause confusion because the following will be possible (core code only for brevity):
```typescript
class DownloadBuilder
{
private …
```

refactor: allow download as stream

---

src/index.ts

Export `storageClientOptions`, so that we can remove the deep import and get CI working again!
Ref: https://github.com/supabase/supabase-js/pull/1567

fix: export storageClientOptions

---

.github/workflows/ci.yml

Add a `fail-on-error: false` to `coveralls` uploads. Change `coverageapp` version used from `master` to `v2`, so that it accepts this input.
Coveralls seems to be failing, and being flaky. 
If `coveralls` upload fails, the CI will not fail.

chore: do not fail on coveralls error
